version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    image: microservices/auth-service:1.0.0
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms512m -Xmx1024m
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-Brane1212}
      - EUREKA_SERVER_URL=http://discovery-service:8761/eureka/
      - JWT_SECRET=${JWT_SECRET:-Ods+vUyBPd5pfgRC9ltie6JZPAhmwTj/8zp2/ti9/0c=}
    volumes:
      - ./logs:/app/logs
    networks:
      - microservices-network
    depends_on:
      discovery-service:
        condition: service_healthy
      postgres-db:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  microservices-network:
    external: true