version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service
    image: microservices/user-service:1.0.0
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/user_db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-Brane1212}
      - EUREKA_SERVER_URL=http://discovery-service:8761/eureka/
    volumes:
      - ./logs:/app/logs
    networks:
      - microservices-network
    depends_on:
      discovery-service:
        condition: service_healthy
      postgres-db:
        condition: service_healthy
    restart: unless-stopped

networks:
  microservices-network:
    external: true